### ISSUE TITLE
Selecting entries with arrow key or "j" / "k" does not work in firefox nightly

### ISSUE THREAD

**Issue by compilenix** [infokiller/web-search-navigator#149]
OS: Fedora Linux 31
Firefox Version: Nightly 78.0a1 (2020-05-28)
Web Search Navigator: 0.3.4

It works with regular Firefox (76.0.1).

**Comment by infokiller** [comment]
Adding @mancze who is maintaining the firefox extension

**Comment by mancze** [comment]
I'm sorry, there are too few details for me to start working on the issue. Could you please provide some more?

- What is the actual behaviour?
- Only arrow keys and "j" and "k" are the issue? Or none of the hotkeys work? Or only certain actions do not work? Try remapping to another keys.
- Keys are silently ignored or another action is performed?
- Is there something we can start with (error message, error in console, crash...)?
- I'm do not use Firefox nightly and I do not know how much stable it is. Is it possible that the bug is in the given browser build instead?

**Comment by compilenix** [comment]
> actual behaviour

nothing happens, i've noticed just now that the selection arrow (added by the exension) is at the bottom of the search result and does not move)
![image](https://user-images.githubusercontent.com/6356150/83543019-0cb31c00-a4fc-11ea-9500-fe2f819fb7a6.png)

> Only arrow keys and "j" and "k" are the issue?

no, issue persists when remapping to other keys.

> error message, error console, crash?

nothing like that.
here is the console log:
![image](https://user-images.githubusercontent.com/6356150/83543592-ef328200-a4fc-11ea-838a-ae26ff9bc977.png)

> hotkeys work?

yes, "i" for switching to image search is working

> possible that the bug is in the given browser build?

yes

**Comment by mancze** [comment]
Thank you. Hmm, it seems that you might be served another version of google search results. It is possible that selectors we use to detect results do not work.

Can you please try extension in an incognito window and/or copy the css path of the search result heading (Right click -> Inspect Element -> Right click on the node -> Copy -> CSS Path)?
![image](https://user-images.githubusercontent.com/1493286/83545661-ce1f6080-a4ff-11ea-8bcf-f31fc841b8e8.png)

**Comment by compilenix** [comment]
Interesting in "incognito window" it works just fine.

This is the CSS path from within incognito:
`html body#gsr.srp.tbo.vasq div#main div#cnt.big div.mw div#rcnt div.col div#center_col div#res.med div#search div div#rso div.g div.rc div.r a.highlighted-search-result h3.LC20lb.DKV0Md`

This is the CSS path from a normal / non-incognito window:
`html body#gsr.srp.tbo.vasq div#main div#cnt.big div.mw div#rcnt div.col div#center_col div#res.med div#search div div#rso div.g div.rc div.r div a h3.LC20lb.DKV0Md`

**Comment by mancze** [comment]
Great, thanks. In your regular browser session there is an extra `div`. That causes that our selectors are not matching the results. Will take look at it. I guess you might be a/b tested or new version is being rolled out.

**Comment by Olshansk** [comment]
Hey,

I was linked to this issue from https://github.com/infokiller/web-search-navigator/issues/148.
I've followed the instructions above to provide some extra information.

Please note that according to https://stackoverflow.com/a/35412554/768439, `Copy CSS Path` has been replace by `Copy Selector` in the newest version of chrome.

Copy selector returns:
```
#rso > div:nth-child(3) > div > div.r > a > h3
```

Copy outer html returns:
```
<h3 class="LC20lb DKV0Md">Fast.com: Internet Speed Test</h3>
```

Here is a screenshot for reference.

![Screen Shot 2020-06-04 at 9 16 56 AM](https://user-images.githubusercontent.com/1892194/83782127-3d9e6880-a644-11ea-873c-438de7166377.png)

**Comment by infokiller** [comment]
Thanks for the details!
From what I can tell the CSS selectors used in the extension should actually match your search results.
Can you please do the following test:
- Search for something
- Go to Inspect Element in the dev console (`Ctrl+Shift+I` usually works)
- Hit `Ctrl+f` (or `Cmd+f` in Mac) which will open a small search box
- Paste `#search .r > a:first-of-type, #search .r g-link > a:first-of-type` and see if you get any matches

Screenshot (the red rectangle marks where you see if there were any matches):

![image](https://user-images.githubusercontent.com/10516814/83923136-4ac56f80-a78a-11ea-9c78-6744f7b4b1be.png)

**Comment by Olshansk** [comment]
That search doesn't seem to bring anything up:

![Screen Shot 2020-06-08 at 8 56 37 AM](https://user-images.githubusercontent.com/1892194/84052854-fb3b9b00-a965-11ea-9270-30b02331609e.png)

**Comment by infokiller** [comment]
It seems that you accidentally copied the word "Paste" as well so the selector in your screenshot is off.
But thinking about it, it may be quicker to figure this out if you can send me the html page you get and I will play around with it.

**Comment by infokiller** [comment]
That's strange, because from your screenshot it looks like it should work with the selectors used by the published Chrome version.
One thing I'd like to check is if the issue is that the arrows don't appear, but the extension actually does find the links. To verify this: when you press Space or Enter, does it follow any link?

If not, please send me the full HTML page so I can test it with the latest version of the extension.

**Comment by compilenix** [comment]
I've had to re-login to my google account and since then it works as it should.

I assume it's what @mancze said earlier:
> Hmm, it seems that you might be served another version of google search results. It is possible that selectors we use to detect results do not work.

Here is the CSS Path I'm getting now, which is the same as i got previously in incognito mode:
`html body#gsr.srp.tbo.vasq div#main div#cnt.big div.mw div#rcnt div.col div#center_col div#res.med div#search div div#rso div.g div.rc div.r a.highlighted-search-result h3.LC20lb.DKV0Md`

For me the issue is "resolved", but i leave it to you how to go forward with this.

Greetings and thanks for the support :+1:

**Comment by infokiller** [comment]
@compilenix thanks for letting use know and glad it's working now!
I'll see if it makes sense to make the selectors more general so that they would have matched the links in the page you were served.

**Comment by Olshansk** [comment]
So if it works for @complienix, why do you think it doesn't work for me?

**Comment by infokiller** [comment]
@Olshansk in case you missed it I replied to you above: https://github.com/infokiller/web-search-navigator/issues/149#issuecomment-643809009

compilenix had a different DOM from yours that wouldn't match the selectors we use (it had an extra div, see https://github.com/infokiller/web-search-navigator/issues/149#issuecomment-638280633)

**Comment by Olshansk** [comment]
`To verify this: when you press Space or Enter, does it follow any link?`

No, nothing happens...

Is there anything else I could try before I send you the full DOM?

**Comment by infokiller** [comment]
You can try to build the extension from the master branch (which was updated since the last Chrome release) and see if it works there. Something like this:
```sh
git clone https://github.com/infokiller/web-search-navigator
cd web-search-navigator
yarn install && yarn build
```

Then load the unpacked extension from the `src` folder.
If you don't want to install/run git/yarn, let me know and I can also send a zip file of the build.
Also let me know if you need help on loading an unpacked chrome extension.

**Comment by Olshansk** [comment]
I'm hitting this issue when trying to load the unpacked extension:

```
~/workspace/web-search-navigator/src
Could not load javascript 'mousetrap.js' for content script.
Could not load manifest.
```

The outputs of by src directory are:
```
background.js                     icon128.png                       icon300.png                       icon48.png                        manifest.json                     options.css                       searchEngines.js
browser-polyfill.js               icon150.png                       icon3264.png                      icon50.png                        mousetrap-global-bind.min.js      options.html                      search_results.css
extension.js                      icon16.png                        icon44.png                        main.js                           mousetrap.min.js                  options.js                        webext-dynamic-content-scripts.js
```

**Comment by infokiller** [comment]
Sorry for that, I broke the build script in one of my last commits.
Can you `git pull` and try again?

**Comment by infokiller** [comment]
@Olshansk I made a few improvements in recent commits, please try the latest master branch (the build should be working now).
You can also try to add youtube and startpage support in the extension options and see if they work.

**Comment by Olshansk** [comment]
Still not working.

Here's my loaded extension:

![Screen Shot 2020-06-20 at 10 02 37 AM](https://user-images.githubusercontent.com/1892194/85207449-a0972d00-b2dd-11ea-9e0a-3e0ea292427f.png)

Here is the error:
![Screen Shot 2020-06-20 at 10 02 54 AM](https://user-images.githubusercontent.com/1892194/85207457-ad1b8580-b2dd-11ea-88d1-cd6c479bacb7.png)

Here is the result of my google search result:
![Screen Shot 2020-06-20 at 10 06 35 AM](https://user-images.githubusercontent.com/1892194/85207462-bf95bf00-b2dd-11ea-9b11-4675eaee48a5.png)

**Comment by infokiller** [comment]
The error you see in the extension is harmless and something you can safely ignore (it complains about a setting that is there only for Firefox).
Not sure what's wrong there.
If you can send me the HTML page (from incognito) and I will try to test it on my machine (just check that it works locally for you).
If I'm not able to reproduce the issue, the only other thing I can think of is adding logging statements that will be enabled with an option.

**Comment by Olshansk** [comment]
[test.zip](https://github.com/infokiller/web-search-navigator/files/4808279/test.zip)

**Comment by infokiller** [comment]
I get an error unpacking it because the filename is too long:

<details>
  <summary>error log</summary>

```
Archive:  test.zip
   creating: Unpack-6898/test/
  inflating: Unpack-6898/test/.DS_Store
  inflating: Unpack-6898/__MACOSX/test/._.DS_Store
   creating: Unpack-6898/test/test - Google Search_files/
  inflating: Unpack-6898/__MACOSX/test/._test - Google Search_files
  inflating: Unpack-6898/test/test - Google Search.htm
  inflating: Unpack-6898/__MACOSX/test/._test - Google Search.htm
  inflating: Unpack-6898/test/test - Google Search_files/rs=ACT90oFWj-cPZFdzJhPaKkBBsjtFQ72f0g
  inflating: Unpack-6898/__MACOSX/test/test - Google Search_files/._rs=ACT90oFWj-cPZFdzJhPaKkBBsjtFQ72f0g
  inflating: Unpack-6898/test/test - Google Search_files/m=QPfswe,Uuupec,UxJOle,r36a9c,xj7LNb
  inflating: Unpack-6898/__MACOSX/test/test - Google Search_files/._m=QPfswe,Uuupec,UxJOle,r36a9c,xj7LNb
  inflating: Unpack-6898/test/test - Google Search_files/rs=AA2YrTu2RI8SdcQMTh62JZue4I0IrPoN_Q
  inflating: Unpack-6898/__MACOSX/test/test - Google Search_files/._rs=AA2YrTu2RI8SdcQMTh62JZue4I0IrPoN_Q
  inflating: Unpack-6898/test/test - Google Search_files/loading_24.gif
  inflating: Unpack-6898/__MACOSX/test/test - Google Search_files/._loading_24.gif
  inflating: Unpack-6898/test/test - Google Search_files/m=ZuqZhb,c3JEL
  inflating: Unpack-6898/__MACOSX/test/test - Google Search_files/._m=ZuqZhb,c3JEL
  inflating: Unpack-6898/test/test - Google Search_files/cb=gapi.loaded_0
  inflating: Unpack-6898/__MACOSX/test/test - Google Search_files/._cb=gapi.loaded_0
  inflating: Unpack-6898/test/test - Google Search_files/rs=AA2YrTuME5s4OF941I3OiInEnTUrGNkFDw
  inflating: Unpack-6898/__MACOSX/test/test - Google Search_files/._rs=AA2YrTuME5s4OF941I3OiInEnTUrGNkFDw
  inflating: Unpack-6898/test/test - Google Search_files/googlelogo_color_92x30dp.png
  inflating: Unpack-6898/__MACOSX/test/test - Google Search_files/._googlelogo_color_92x30dp.png
  inflating: Unpack-6898/test/test - Google Search_files/m=F8FRnd,G3eKy,Lt3RDf,MB3mMb,MkHyGd,NBZ7u,NpD4ec,OG6ZHd,RqxLvf,T6sTsf,T7XTS,TxZWcc,URQPYc,XMgU6d,XjCeUc,aCZVp,aa,aam1T,abd,async,bgd,dvl,eN4qad,eT9j9d,fEVMic,foot,iD8Yk,kyn,lu,m,m6a0l,mUpTid,mpck,mu,o02Jie,pB6Zqd,qik19b,rHjpXd,runuse,sb_wiz,sf,sonic,spch,
error:  cannot create Unpack-6898/__MACOSX/test/test - Google Search_files/._m=F8FRnd,G3eKy,Lt3RDf,MB3mMb,MkHyGd,NBZ7u,NpD4ec,OG6ZHd,RqxLvf,T6sTsf,T7XTS,TxZWcc,URQPYc,XMgU6d,XjCeUc,aCZVp,aa,aam1T,abd,async,bgd,dvl,eN4qad,eT9j9d,fEVMic,foot,iD8Yk,kyn,lu,m,m6a0l,mUpTid,mpck,mu,o02Jie,pB6Zqd,qik19b,rHjpXd,runuse,sb_wiz,sf,sonic,spch,
        File name too long
aunpack: unzip ...: non-zero return-code
```
</details>

BTW, did you test the extension in Firefox?
I found that there is a very nice way to run the extension automatically in a separate browser profile in a single command (supports both Chrome and Firefox):

```sh
# Verify master branch is up to date
git pull
yarn install && yarn build
# Replace '--target chromium' with "--target firefox-desktop" for Firefox.
yarn run web-ext run --source-dir src --start-url 'https://www.google.com/search?q=whatever' --target chromium
```

**Comment by Olshansk** [comment]
1. The yarn command required me to install web-ext first:

`npm install web-ext`

2. Here is the output of `yarn run web-ext run --source-dir src --start-url 'https://www.google.com/search?q=whatever' --target chromium`:
[whatever.zip](https://github.com/infokiller/web-search-navigator/files/4808574/whatever.zip)

Still didn't work. Note that I deleted a few of the long filenames.

3. Works fine on firefox.

**Comment by infokiller** [comment]
> 1. The yarn command required me to install web-ext first:
> 
> `npm install web-ext`

That should have been handled by the `git pull` and `yarn install`, not sure why it didn't work.

> 
> 1. Here is the output of `yarn run web-ext run --source-dir src --start-url 'https://www.google.com/search?q=whatever' --target chromium`:
>    [whatever.zip](https://github.com/infokiller/web-search-navigator/files/4808574/whatever.zip)

Thanks, unfortunately I can't reproduce it :(

![image](https://user-images.githubusercontent.com/10516814/85212664-aaf90b80-b35d-11ea-8dec-9ec9742ecfea.png)

> 
> Still didn't work. Note that I deleted a few of the long filenames.
> 
> 1. Works fine on firefox.

**Comment by infokiller** [comment]
The only other thing I can think of is to add very detailed logging, then have you run it and check the output.
I can quickly push a test branch with this code, and then you can run `git pull && git checkout debug` to get it.
Are you up to it?
Sorry for all the trouble, not being able to reproduce it is making it hard.

**Comment by Olshansk** [comment]
Definitely. We've already spent so much time on this we should get to the bottom of it!

**Comment by infokiller** [comment]
That's the spirit! I'll add detailed logging and send you an archive to extract and load.

**Comment by infokiller** [comment]
Alright, I added logging and pushed it to a separate branch: `debug-149`. Please run this as following from your local git repo directory:

```
git checkout debug-149
git pull origin debug-149
yarn run web-ext run --source-dir src --start-url 'https://www.google.com/search?q=whatever' --target chromium
```

And then check the dev console for logs that start with `wsn: `. Here's what I'm seeing:

![image](https://user-images.githubusercontent.com/10516814/85277174-a29eee80-b48b-11ea-8277-3b3284763c32.png)

**Comment by infokiller** [comment]
Alright, I added logging and pushed it to a separate branch: `debug-149`. Please run this as following from your local git repo directory:

```
git checkout debug-149
git pull origin debug-149
yarn run web-ext run --source-dir src --start-url 'https://www.google.com/search?q=whatever' --target chromium
```

And then check the dev console for logs that start with `wsn: `. Here's what I'm seeing:

![image](https://user-images.githubusercontent.com/10516814/85277288-d2e68d00-b48b-11ea-8bda-b6eba8bc23cc.png)

**Comment by Olshansk** [comment]
@infokiller Sorry for the delay on this, but I finally managed to run the branch you created. I'm seeing an error but no logs prefixed with wsn.

<img width="1904" alt="Screen Shot 2020-06-25 at 9 59 38 PM" src="https://user-images.githubusercontent.com/1892194/85822217-33e1bf80-b72f-11ea-9ce2-e118c11724e1.png">

**Comment by infokiller** [comment]
No worries, thanks for trying that.
This error looks unrelated, it seems like the extension isn't activated by Chrome for some reason. In the devtools if you go to "Sources" tab and then the "Content scripts" section, do you see the extension?
Here's how it looks on my computer:
![image](https://user-images.githubusercontent.com/10516814/85881063-b5942480-b7e5-11ea-81b4-005a8054683a.png)

**Comment by Olshansk** [comment]
I've confirmed that `/web-search-navigator/src` has all the necessary files, but nothing shows up under content scripts!

I execute it via `yarn run web-ext run --source-dir src --start-url 'https://www.google.com/search?q=whatever' --target chromium`.

![Screen Shot 2020-06-26 at 5 49 11 PM](https://user-images.githubusercontent.com/1892194/85910716-5f1eea00-b7d5-11ea-80ae-58b121dd3d69.png)

**Comment by infokiller** [comment]
Thanks for the screenshots, they're very helpful.
Yes, launching it with `web-ext` is the best way to test it, keep doing that.
Let's try to figure out why the content script is not loaded. Content scripts are loaded based on the URL and the extension manifest, so let's check that:

- What is the full URL that you see when you click on the address bar? You need to click on the address bar because Chrome can hide `www.` and other stuff.
- When you go to the extension settings (right click extension icon, then "Manage extensions"), in the "Site access" section, do you see the `*://www.google.com/*` enabled?
  Here's how it looks for me:

![image](https://user-images.githubusercontent.com/10516814/85916976-94234f00-b85e-11ea-82e5-de5a2e166464.png)

And after a long list of Google URLs for different domains there's the `google.com` one:

![image](https://user-images.githubusercontent.com/10516814/85916990-bcab4900-b85e-11ea-8352-f2e79769b3d9.png)

**Comment by Olshansk** [comment]
> What is the full URL that you see when you click on the address bar? You need to click on the address bar because Chrome can hide www. and other stuff.

https://www.google.com/search?q=whatever

> When you go to the extension settings (right click extension icon, then "Manage extensions"), in the "Site access" section, do you see the *://www.google.com/* enabled?

Yup!

![Screen Shot 2020-06-27 at 10 06 17 AM](https://user-images.githubusercontent.com/1892194/85927904-e4e67800-b85d-11ea-9c34-31f02e54163a.png)

**Comment by infokiller** [comment]
It seems like the problem may be that your Google URL doesn't have the `www.` prefix. This is strange... Maybe Google is experimenting with removing it.
Can you check that this is the case when you put the cursor at the end of the URL in the address bar?

Here's how it looks for me without selecting it (the `www.` is hidden):
![image](https://user-images.githubusercontent.com/10516814/85928960-ada5b480-b8b9-11ea-86c8-779b00f2fda7.png)

Then when only selecting it (still hidden):

![image](https://user-images.githubusercontent.com/10516814/85928953-a8486a00-b8b9-11ea-8204-b471546d68ba.png)

And it only shows up when the cursor is at the end:

![image](https://user-images.githubusercontent.com/10516814/85928996-e04fad00-b8b9-11ea-98b8-ea25258f0512.png)

**Comment by infokiller** [comment]
I just pushed a change to the `debug-149` branch that makes the extension handle a missing `www.` (though we didn't verify yet if this is indeed the issue). You can try the new version using:

```sh
git pull origin debug-149
yarn run web-ext run --source-dir src --start-url 'https://www.google.com/search?q=whatever' --target chromium
```

Then like before, check if the content script is loaded.
If that still doesn't work, try to check if `co.uk` works:

```sh
yarn run web-ext run --source-dir src --start-url 'https://www.google.co.uk/search?q=whatever' --target chromium
```

(And again, check if the content script is loaded)

**Comment by Olshansk** [comment]
Progress! However, the extension still doesn't work...

The content script was loaded:
<img width="1904" alt="Screen Shot 2020-06-27 at 2 38 01 PM" src="https://user-images.githubusercontent.com/1892194/85932770-e6c33200-b883-11ea-82a7-f7f98ea6132e.png">

And we even had some logging:
<img width="1904" alt="Screen Shot 2020-06-27 at 2 38 17 PM" src="https://user-images.githubusercontent.com/1892194/85932767-e1fe7e00-b883-11ea-8fc5-e73bf90d690b.png">

**Comment by infokiller** [comment]
Based on the logs it should work, but you may not see the search result highlighting because it doesn't select dictionary results or people also ask. There was also an issue with video results that I fixed and merged into the debug branch, so please run `git pull origin debug-149` again. Questions:

1. Can you please report the full `google.com` URL that you see when you put your cursor at the end of the search input? See https://github.com/infokiller/web-search-navigator/issues/149#issuecomment-650593446 for screenshots of what I mean.
2. Can you please try to use the arrow keys in `google.co.uk`, where you see the logs?
3. Can you please check if you now see the logs in `google.com` (after running `git pull origin debug-149` and rerunning the `yarn run web-ext` command)?

**Comment by Olshansk** [comment]
> 1. Can you please report the full google.com URL that you see when you put your cursor at the end of the search input? See #149 (comment) for screenshots of what I mean.

https://www.google.co.uk/search?q=whatever

<img width="1904" alt="Screen Shot 2020-06-28 at 8 44 47 PM" src="https://user-images.githubusercontent.com/1892194/85970751-3c7d0480-b980-11ea-9bf7-1b8119a259c0.png">

> 2. Can you please try to use the arrow keys in google.co.uk, where you see the logs?

It works!

> Can you please check if you now see the logs in google.com (after running git pull origin debug-149 and rerunning the yarn run web-ext command)?

Doesn't work on `google.com`, but the exact same code & flow works on `google.co.uk`. I confirmed that the content script is not being loaded.

<img width="1904" alt="Screen Shot 2020-06-28 at 8 49 11 PM" src="https://user-images.githubusercontent.com/1892194/85970984-dcd32900-b980-11ea-91a2-fed83a769365.png">

**Comment by infokiller** [comment]
I'm baffled... it works in `google.com` in Firefox, but not in Chrome. But then in Chrome it works in `google.co.uk` and not `google.com`, even though the permissions seem to be set correctly (as seen in the extension page).

**Comment by Olshansk** [comment]
I reloaded the extension using web-ext reloaded and tried a lot of different domains that I found in the `manifest.json` file. All of them worked except for `.com`.

For `.com`, the extension was greyed out and the content scripts weren't loaded. 

Do you have any other suggestions for avenues I could investigate?

**Comment by infokiller** [comment]
I don't have very good ideas, but here's what I would test:

1. Run the `web-ext run` command, and then when you're in the `google.com` page, execute in the Chrome dev console `Boolean(window.location.href.match(/\/\www\.google\.com\/search/))` and report if it prints `true` or `false`
2. What does `chrome://version` report?
3. Can you test [Chrome Beta](https://www.google.com/chrome/beta/) or Chromium (the pure OSS version of Chrome)?

**Comment by Olshansk** [comment]
1. `true`
2. `83.0.4103.116 (Official Build) (64-bit)`
3. Given my findings above, I actually just discovered that my normal chrome with the normal app installed works on all google domains except for `.com` where the content scripts don't get loaded.

I think it's time to give up...

**Comment by infokiller** [comment]
Alright, sorry I wasn't able to resolve it /:
